// class Player {
//     constructor(x, y, w, h, c, xSpeed, ySpeed) {
//         this.x = x;
//         this.y = y;
//         this.w = w;
//         this.h = h;
//         this.c = c;
//         this.xSpeed = xSpeed;
//         this.ySpeed = ySpeed

//     }
//     draw() {
//         ctx.fillStyle = this.c
//         ctx.fillRect(this.x, this.y, this.w, this.h)
//     }
//     move() {
//         this.x += this.xSpeed
//         // if (leftKeyPressed && this.x > 0) {
//         //     this.x -= this.xSpeed
//         // }
//         // if (rightKeyPressed && this.x + this.w < canvas.width) {
//         //     this.x += this.xSpeed
//         // }
//     }

// }